### ISSUE TITLE
model_name and class_name options are not respected

### ISSUE THREAD

**Issue by xtian** [JSONAPI-Resources/jsonapi-resources#525]
As a result of #507, `Resource.model_name` and the `class_name` option of `Resource.has_many` are no longer respected.

For instance, requests for authors in this example will still be serialized using `UserResource` and so include `email` in their attributes hash.

``` ruby
class UserResource < JSONAPI::Resource
  attributes :first_name, :email  
end

class AuthorResource < JSONAPI::Resource
  model_name 'User'
  attributes :first_name
end
```

Likewise, the authors in this example will be serialized using `UserResource` and so include `email` in their attributes hashes as well.

``` ruby
class Book < ActiveRecord::Base
  has_many :authors, class_name: 'User'
end

class BookResource < JSONAPI::Resource
  has_many :authors, class_name: 'Author'
end
```

There are a few changes I think caused this, but there might be more:
- https://github.com/cerebris/jsonapi-resources/pull/507/files#diff-e6cf31c573bd5f2277b1f16812943df4L505
- https://github.com/cerebris/jsonapi-resources/pull/507/files#diff-e6cf31c573bd5f2277b1f16812943df4L517
- https://github.com/cerebris/jsonapi-resources/pull/507/files#diff-e6cf31c573bd5f2277b1f16812943df4L814

**Comment by lgebhardt** [comment]
Could you please check if the newest release fixes this for you?

**Comment by xtian** [comment]
@lgebhardt No, it doesn't seem to fix this.

It works if I overwrite `Resource.find_by_key` with this implementation:

``` ruby
 def self.find_by_key(key, options = {})
  context = options[:context]
  records = records(options)
  records = apply_includes(records, options)
  model = records.where({_primary_key => key}).first
  fail JSONAPI::Exceptions::RecordNotFound.new(key) if model.nil?
  self.new(model, context)
end
```

But I should also note that there are other bugs/breaking changes that are preventing us from upgrading from 0.5.9 that I haven't had time to track down yet.

**Comment by thewalkingtoast** [comment]
I'm running into this as well and can reproduce with @xtian's samples. I'm also using `0.6.2`.

**Comment by lgebhardt** [comment]
@xtian and @thewalkingtoast could you look at #554 and see if this fixes the issue for you?

**Comment by xtian** [comment]
@lgebhardt Yeah it seems to fix it. Thanks!

**Comment by thewalkingtoast** [comment]
@lgebhardt Working for me as well. :+1: Thank you!

**Comment by xtian** [comment]
@lgebhardt One thing I've found that isn't working is that the `type` field on a serialized resource object is still being derived from the model class rather than the resource.

**Comment by lgebhardt** [comment]
@xtian Could you provide a little more detail on the `type` field issue?

**Comment by xtian** [comment]
For instance, in a situation like this—

``` ruby
class Book < ActiveRecord::Base
  has_many :authors, class_name: 'User'
end

class AuthorResource < JSONAPI::Resource
  model_name 'User'
  attributes :first_name
end

class BookResource < JSONAPI::Resource
  has_many :authors, class_name: 'Author'
end
```

—the `type` field ([as described here](http://jsonapi.org/format/#document-resource-object-identification)) for each author returned from `BookResource` will be `"users"` whereas in 0.5.9 it would be `"authors"`.

**Comment by lgebhardt** [comment]
Thanks. I'll look into it.

**Comment by lgebhardt** [comment]
@xtian I've updated the code and I think it should now behave the way it used to. Could you please check again?

**Comment by xtian** [comment]
@lgebhardt I'm still getting the wrong type using 1ec10ece33d26c958cb45038f4b397c4552bb9f5

The `source` being passed to [`object_hash`](https://github.com/cerebris/jsonapi-resources/blob/796241ee99404e9ee5cc0b171749f9d115cb6561/lib/jsonapi/resource_serializer.rb#L114) is still a `UserResource` even though I have `class_name` specified on the `has_many`. Not sure if I need to change anything in my code to make it work, but let me know if I do.

**Comment by lgebhardt** [comment]
@xtian Sorry about that. I ended up fixing more than I had planned to (found another major bug when testing the new changes). I thought I had split the two apart, but I see now I didn't get the fix into the branch. I've just pushed the rest of the changes to the same branch since it looks like it will be harder than I thought to separate them at this point. So if you wouldn't mind testing this again I'd appreciate it.

**Comment by xtian** [comment]
@lgebhardt Yeah it seems to work now—thanks a lot for your help! I was able to iron out the other issues I mentioned a couple weeks ago as well. Everything else ended up being small changes or dumb stuff we were doing.

I did end up adding the following to our Resources which deal with STI models:

``` ruby
def self.resource_for_model(*); self; end
```

Not sure whether that is an appropriate solution or not, but the model subclasses don't diverge at all in terms of how they are modified so I thought `immutable` with a resource for each one would be a little much right now.
