### ISSUE TITLE
Rails 5: Uninitialized constant ActionDispatch::ParamsParser::DEFAULT_PARSERS (NameError)

### ISSUE THREAD

**Issue by ashaniray** [JSONAPI-Resources/jsonapi-resources#681]
We encounter the following error in Rails 5:

Prerequisite:
- adding JSON api resourses in gem file
- bundle installing Rails 5

On executing `rails generate model` we get the following error:

```
/usr/local/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.7.0/lib/jsonapi/mime_types.rb:7:in `<top (required)>': uninitialized constant ActionDispatch::ParamsParser::DEFAULT_PARSERS (NameError)
    from /usr/local/lib/ruby/gems/2.2.0/gems/jsonapi-resources-0.7.0/lib/jsonapi-resources.rb:10:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:76:in `require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:72:in `each'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:72:in `block in require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:61:in `each'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:61:in `require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:134:in `require'
    from /Users/rsstorg/Programs/ruby/rails/movieapi/config/application.rb:17:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/application.rb:82:in `require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/application.rb:82:in `preload'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/application.rb:143:in `serve'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

**Comment by Tonkpils** [comment]
This also happens when generating a new resource

**Comment by Tonkpils** [comment]
This was fixed by upgrading to `jsonapi-resources` `0.7.1.beta1`

**Comment by wyaeld** [comment]
I tried updating to that version, but still get the same error.

`0.7.1.beta2` works however
